### get boards
GET http://localhost:8080/api/board

### get board
GET http://localhost:8080/api/board/1

### create board
POST http://localhost:8080/api/board
Content-Type: application/json

{
  "title": "Example Title",
  "subtitle": "Example Subtitle",
  "content": "This is an example content for the board.",
  "boardType":  "GENERAL",
  "location": "BUSAN",
  "anonymousStatus": "true"
}


### update board
PUT http://localhost:8080/api/board/1
Content-Type: application/json

{
  "title": "Update Title",
  "subtitle": "Update Subtitle",
  "content": "This is an Update content for the board.",
  "boardType":  "Update GENERAL",
  "location": "Update BUSAN",
  "anonymousStatus": "Update true"
}

### delete board
DELETE http://localhost:8080/api/board/1
