### get boards
GET http://localhost:8080/api/v1/board?page=0&size=10&sortDirection=DESC&sortBy=id
Cookie: Authorization=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJrYWthbzM3Mjk0MzgwNTIiLCJpYXQiOjE3Mjc5MzM4MjcsImV4cCI6MjQxNzI3OTMzODI3fQ.LvKK8vbExt91eIqU-rfsdvYE0JqC1MUlsK7gdRE72co

### get board
GET http://localhost:8080/api/v1/board/1

### create board
POST http://localhost:8080/api/v1/board
Content-Type: application/json
Cookie: Authorization={{Authorization}}

{
  "title": "Example Title",
  "content": "This is an example content for the board.",
  "board_type": "ENTIRE",
  "location": "BUSAN",
  "anonymous_status": "PRIVATE"
}


### update board
PUT http://localhost:8080/api/v1/board/1
Content-Type: application/json
Cookie: Authorization=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJrYWthbzM3Mjk0MzgwNTIiLCJpYXQiOjE3Mjc5MzM4MjcsImV4cCI6MjQxNzI3OTMzODI3fQ.LvKK8vbExt91eIqU-rfsdvYE0JqC1MUlsK7gdRE72co

{
  "title": "Update Title",
  "subtitle": "Update Subtitle",
  "content": "This is an Update content for the board.",
  "boardType":  "Update GENERAL",
  "location": "Update BUSAN",
  "anonymousStatus": "Update true"
}

### delete board
DELETE http://localhost:8080/api/v1/board/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJrYWthbzM3Mjk0MzgwNTIiLCJpYXQiOjE3Mjc4NjE2NjUsImV4cCI6MTcyNzg2NDA2NX0.Lc3gVOdsj_D3Zn_y6bvMRipYMCr_IenbLm1XVPi8Rr4
