### get template
GET http://localhost:8080/api/template/1

### get kakao code
GET http://localhost:8080/api/auth/login

### get template
GET http://localhost:8080/api/member/2

### create member
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "password": "password5",
  "email": "kakao384747484",
  "member_type": "user",
  "insurance_status": "Y",
  "return_deposit": "5000",
  "safety_score": "80",
  "profile_image": "example.jpg",
  "progress_step": "step3",
  "created_at": "2024-09-26 02:31",
  "updated_at": "2024-09-26 03:31",
  "is_deleted": "N"
}

### create member
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "password": "password3",
  "email": "email5@naver.com"
}


### update member
PUT http://localhost:8080/api/member/1
Content-Type: application/json

{
  "password": "password5"
}

### delete member
DELETE http://localhost:8080/api/member/1
