version: 0.0
os: linux
files:
  - source: libs/
    destination: /home/ubuntu/my-spring-app/libs/
  - source: scripts/
    destination: /home/ubuntu/my-spring-app/scripts/
  - source: fonts/    # 폰트 디렉토리 추가
    destination: /home/ubuntu/my-spring-app/fonts/
permissions:
  - object: /home/ubuntu/my-spring-app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
