### get best boards
GET http://localhost:8080/api/v1/board/best?
    size=5&board_type=ENTIRE&content_length=10
Authorization: {{Authorization}}


### get boards
GET http://localhost:8080/api/v1/board?
    page=0&size=1&sort_direction=DESC&sort_by=id&board_type=ENTIRE&content_length=10
Authorization: {{Authorization}}

### get board
GET http://localhost:8080/api/v1/board/1

### create board
POST http://localhost:8080/api/v1/board
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{Authorization}}

--boundary
Content-Disposition: form-data; name="images"; filename="test1.png"
Content-Type: image/png

< /Users/jaebin/Desktop/test1.png

--boundary
Content-Disposition: form-data; name="images"; filename="test2.png"
Content-Type: image/png

< /Users/jaebin/Desktop/test2.png

--boundary--


### update board
PUT http://localhost:8080/api/v1/board/1
Content-Type: application/json
Cookie: Authorization=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5IiwiZW1haWwiOiJqaW4wMTEyMjhAbmF2ZXIuY29tIiwiaWF0IjoxNzMwNzE1MDYwLCJleHAiOjI0MTczMDcxNTA2MH0.9dGtao-8IvUSIVXKj9EqDDSKxQbRgn2qvBs4OfvWXxA

{
  "title": "Example Title",
  "content": "a.",
  "board_type": "ENTIRE",
  "location": "BUSAN",
  "anonymous_status": "PRIVATE"
}

### delete board
DELETE http://localhost:8080/api/v1/board/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5IiwiZW1haWwiOiJqaW4wMTEyMjhAbmF2ZXIuY29tIiwiaWF0IjoxNzMwNzE1MDYwLCJleHAiOjI0MTczMDcxNTA2MH0.9dGtao-8IvUSIVXKj9EqDDSKxQbRgn2qvBs4OfvWXxA