### get templates
GET http://localhost:8080/api/template

### get template
GET http://localhost:8080/api/template/1

### create template
POST http://localhost:8080/api/template
Content-Type: application/json

{
  "templateColumn1": "col1",
  "templateColumn2": "col2"
}

### update template
PUT http://localhost:8080/api/template/1
Content-Type: application/json

{
  "templateColumn1": "update_col1",
  "templateColumn2": "update_col2"
}

### delete template
DELETE http://localhost:8080/api/template/1
